language: python
python:
  - "3.6"
  - "3.7"
  - "2.7"

os: linux
dist: xenial
sudo: required

branches:
  only:
  - master

# command to install dependencies
install:
  - pip install -r requirements.txt
  # Enable running MPI tests
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip install mpi4py
  # Use black for style checking (Python3 only)
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^[3-9].+" ]]; then
      echo installing black for Python $TRAVIS_PYTHON_VERSION;
      pip install black;
    else
      echo Python is python2 so not using black;
    fi
  # Use codespell for spell checking
  - pip install codespell

# command to run tests
jobs:
  include:
    - stage: test
      script: pytest -s --cov=jobqueue_features
    - stage: spelling
      script: 
        - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^[3-9].+" ]]; then
            black --check .;
          else
            echo Python is python2 so not using black;
          fi
    - stage: style
      script: codespell --quiet-level=2
