language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

os: linux
dist: xenial
sudo: required

branches:
  only:
  - master

# command to install dependencies
install:
  # Enable running MPI tests (and installing MPI4PY)
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -s --cov=jobqueue_features

jobs:
  include:
    - stage: style
      python:
        - "3.7"
      # Use black for style checking (Python3 only)
      install:
        - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^[3-9].+ ]]; then
            echo installing black for Python $TRAVIS_PYTHON_VERSION;
            pip install black;
          else
            echo Python is $TRAVIS_PYTHON_VERSION so not using black;
          fi
      script: 
        - if [[ "$TRAVIS_PYTHON_VERSION" =~ ^[3-9].+ ]]; then
            black --check .;
          else
            echo Python is $TRAVIS_PYTHON_VERSION so not using black;
          fi

    - stage: spelling
      python:
        - "3.7"
      # Use codespell for spell checking
      install:
        pip install codespell
      script: codespell --quiet-level=2
