language: python
python:
  - "3.6"
  - "3.7"
  - "2.7"

os: linux
dist: xenial
sudo: required

# command to install dependencies
install:
  - pip install -r requirements.txt
  # Enable running MPI tests
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip install mpi4py
  # Use black for style checking (Python3 only)
  - echo "TRAVIS_PYTHON_VERSION: $TRAVIS_PYTHON_VERSION"
  - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^[3-9].+" ]]; then
      echo installing black;
      pip install black;
    else
      echo nope;
    fi
  # Use codespell for spell checking
  - pip install codespell

# command to run tests
jobs:
  include:
    - stage: test
      script: pytest -s --cov=jobqueue_features
    - stage: spelling
      script: 
        - echo "TRAVIS_PYTHON_VERSION: $TRAVIS_PYTHON_VERSION"
        - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^[3-9].+" ]]; then
            black --check .;
          else
            echo nope;
          fi
    - stage: style
      script: codespell --quiet-level=2
