language: python
os: linux
dist: xenial
sudo: required

services:
  - docker

python:
  - "3.6"
  - "3.7"

branches:
  only:
  - master

notifications:
  email: false

matrix:
  include:
          #    - python: "3.6"
          #      env:
          #        - OS=ubuntu-14.04
          #        - JOBQUEUE=sge
          #    - python: "3.6"
          #      env:
          #        - OS=ubuntu-14.04
          #        - JOBQUEUE=pbs
    - env:
        - OS=ubuntu-16.04
        # JOBQUEUE=none is for tests that do not need a cluster to run
        - JOBQUEUE=none
    - python: "3.6"
      env:
        - OS=ubuntu-16.04
        - JOBQUEUE=slurm

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.6.0

before_install:
  - set -e
  - pwd
  # Init jobqueue environment: load init and test methods
  - source ci/${JOBQUEUE}.sh
  - jobqueue_before_install
  - set +e
install:
  - set -e
  - jobqueue_install
  - set +e
script:
  - set -e
  - jobqueue_script
  - set +e
after_script:
  - jobqueue_after_script
