version: "2.2"

services:

  master:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.8}
    container_name: pbs-master
    hostname: pbs-master
    volumes:
      - ../..:/jobqueue_features
    command: bash /run-master.sh

  slave-one:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.8}
    container_name: pbs-slave-1
    hostname: pbs-slave-1
    volumes:
      - ../..:/jobqueue_features
    entrypoint: "bash /slave-entrypoint.sh"
    command: bash /run-slave.sh
    links:
      - "master:pbs-master"
    environment:
      - PBS_MASTER=pbs-master
    depends_on:
      - master

  slave-two:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.8}
    container_name: pbs-slave-2
    hostname: pbs-slave-2
    volumes:
      - ../..:/jobqueue_features
    entrypoint: "bash /slave-entrypoint.sh"
    command: bash /run-slave.sh
    links:
      - "master:pbs-master"
    environment:
      - PBS_MASTER=pbs-master
    depends_on:
      - master
