FROM ubuntu:14.04

ENV LANG C.UTF-8

RUN apt-get update && apt-get install curl bzip2 git gcc -y --fix-missing

RUN curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash miniconda.sh -f -b -p /opt/anaconda && \
    /opt/anaconda/bin/conda clean -tipy && \
    rm -f miniconda.sh
ENV PATH /opt/anaconda/bin:$PATH
ARG PYTHON_VERSION
RUN conda install --yes -c conda-forge python=$PYTHON_VERSION flake8 black pytest pytest-asyncio
# Install OpenMPI and mpi4py
RUN conda install --yes -c conda-forge python=$PYTHON_VERSION openmpi mpi4py && conda clean -tipy
# Install latest jobqueue
# RUN pip install git+https://github.com/dask/jobqueue --upgrade --no-deps

COPY ./setup-slave.sh /
COPY ./*.sh /
RUN bash ./setup-slave.sh
