# base image
FROM daskdev/dask-jobqueue:sge-slave
LABEL description="jobqueue_features customisation of dask_jobqueue CI images"

# Some customisation on jobqueue base images
ENV PBS_MASTER pbs-master

# Install OpenMPI and mpi4py (and black)
RUN conda install --yes -c conda-forge black openmpi mpi4py && conda clean -tipy

COPY ./setup-slave.sh /
COPY ./*.sh /
RUN bash ./setup-slave.sh
