version: "2.1"

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile-master
    container_name: sge-master
    hostname: sge-master
    #network_mode: host
    volumes:
      - ../..:/jobqueue_features
    command: bash /run-master.sh

  slave-one:
    build:
      context: .
      dockerfile: Dockerfile-slave
    container_name: slave-one
    hostname: slave-one
    #network_mode: host
    volumes:
      - ../..:/jobqueue_features
    command: bash /run-slave.sh
    links:
      - "master:sge-master"
    depends_on:
      - master

  slave-two:
    build:
      context: .
      dockerfile: Dockerfile-slave
    container_name: slave-two
    hostname: slave-two
    #network_mode: host
    volumes:
      - ../..:/jobqueue_features
    command: bash /run-slave.sh
    links:
      - "master:sge-master"
    depends_on:
      - master
