# base image
FROM daskdev/dask-jobqueue:sge
LABEL description="jobqueue_features customisation of dask_jobqueue CI images"

# Some customisation on jobqueue base images

# Install OpenMPI and mpi4py (and black)
RUN conda install --yes -c conda-forge black openmpi mpi4py && conda clean -tipy

COPY ./*.sh /
COPY ./*.txt /
RUN bash ./setup-master.sh

# expose ports
EXPOSE 8000
EXPOSE 6444
EXPOSE 6445
EXPOSE 6446

ENV SGE_ROOT /var/lib/gridengine/
ENV SGE_CELL default
