name: jobqueue_features
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - dask
  - distributed
  - dask-jobqueue
  - flake8
  - black
  - pytest
  - pytest-ordering
  - pytest-asyncio
  - pytest-cov
